### ISSUE TITLE
Create a dynamic calendar.

### ISSUE THREAD

**Issue by Aahmed-Hossain** [team-consolers/wallet-expert#4]
<img width="778" alt="image" src="https://github.com/team-consolers/wallet-expert/assets/138388233/a8acb22c-acec-42df-b699-3567be7e93c1">

please add the calendar at dashboard/calendar route.

<img width="955" alt="image" src="https://github.com/team-consolers/wallet-expert/assets/138388233/461c8c80-5eda-4e21-80a1-2f7cce945661">

**Comment by tofail-ahmed** [comment]
calendar UI done
